#!/bin/bash
##SCRIPT HUAWEI##

apt update
apt install -y ruby screen figlet toilet cowsay lolcat boxes  > /dev/null 2>&1
toilet -w 100 -f smmono9 Zuke ISP | lolcat
toilet -w 82 -f mini Iniciando... | lolcat
apt install python3-pip
pip3 install bs4
pip3 install requests
pip3 install cloudscraper
cd /temp/
wget https://github.com/luucasamaral/huaweipon/archive/refs/heads/main.zip
apt install unzip
unzip main.zip
